services:
  db:
    image: postgres:15
    container_name: employee_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-employee_db}
    ports:
      - "5400:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: employee_api_web
    command: >
      sh -c "
        until python -c 'import psycopg2; psycopg2.connect(
          dbname=\"${POSTGRES_DB}\",
          user=\"${POSTGRES_USER}\",
          password=\"${POSTGRES_PASSWORD}\",
          host=\"db\",
          port=5432
        )'; do
          echo 'Waiting for database...';
          sleep 2;
        done;
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "
    volumes:
      - ./:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      SECRET_KEY: ${SECRET_KEY}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      LOG_LEVEL: ${LOG_LEVEL}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata: